"Type: Feature":
  - head-branch: ["^feat(ure)?-"]
"Type: Bug":
  - head-branch: ["^fix-"]
"Type: Security":
  - head-branch: ["^sec(urity)?-"]
"Type: Documentation":
  - head-branch: ["^doc(ument)?s?-"]
"Type: Refactoring":
  - head-branch: ["^refactor(ing)?-"]
"Type: Testing":
  - head-branch: ["^test(ing|s)?-"]
"Type: Maintenance":
  - head-branch: ["^maintenance-", "^maintain(ing)?-"]
"Type: CI":
  - head-branch: ["^ci-"]
"Type: Dependencies":
  - head-branch: ["^dep(endency|endencies|s)?-", "^pre-commit-ci-update-config$"]
"Type: Meta":
  - head-branch: ["^meta-"]
