version: v1

labels:
  - label: 🧨 Breaking Change
    matcher:
      commits: '^\w+(\(.+\))?!:\s.+'
  - label: 🎉 New Feature
    matcher:
      commits: '^feat(\(.+\))?!?:\s.+'
  - label: 🧰 Bug
    matcher:
      commits: '^fix(\((?!deps).+\))?!?:\s.+'
  - label: 📖 Documentation
    matcher:
      commits: '^docs(\(.+\))?!?:\s.+'
  - label: 🎨 Style
    matcher:
      commits: '^style(\(.+\))?!?:\s.+'
  - label: 🧹 Refactoring
    matcher:
      commits: '^refactor(\(.+\))?!?:\s.+'
  - label: 🏎️ Performance
    matcher:
      commits: '^perf(\(.+\))?!?:\s.+'
  - label: 🧪 Testing
    matcher:
      commits: '^test(\(.+\))?!?:\s.+'
  - label: 🔨 Build
    matcher:
      commits: '^build(\(.+\))?!?:\s.+'
  - label: 🎽 CI
    matcher:
      commits: '^ci(\(.+\))?!?:\s.+'
  - label: 🔧 Maintenance
    matcher:
      commits: '^chore(\((?!deps).+\))?!?:\s.+'
  - label: ◀️ Revert
    matcher:
      commits: '^revert(\(.+\))?!?:\s.+'
