alwaysReplace: true

customLabels:
  - text: "- [x] 🎉 New Feature"
    label: 🎉 New Feature
  - text: "- [x] 🧰 Bug"
    label: 🧰 Bug
  - text: "- [x] 🛡️ Security"
    label: 🛡️ Security
  - text: "- [x] 📖 Documentation"
    label: 📖 Documentation
  - text: "- [x] 🏎️ Performance"
    label: 🏎️ Performance
  - text: "- [x] 🧹 Refactoring"
    label: 🧹 Refactoring
  - text: "- [x] 🧪 Testing"
    label: 🧪 Testing
  - text: "- [x] 🔧 Maintenance"
    label: 🔧 Maintenance
  - text: "- [x] 🎽 CI"
    label: 🎽 CI
  - text: "- [x] 🧠 Meta"
    label: 🧠 Meta
  - text: "chore(deps): "
    label: ⛓️ Dependencies
  - text: "Release: v"
    label: 🚀 Release
