alwaysReplace: true
searchTitle: true
searchBody: true

customLabels:
  - text: "- [x] 🎉 Feature"
    label: "🎉 Feature"
  - text: "- [x] 🧰 Bug"
    label: "🧰 Bug"
  - text: "- [x] 🛡️ Security"
    label: "🛡️ Security"
  - text: "- [x] 📖 Documentation"
    label: "📖 Documentation"
  - text: "- [x] 🧹 Refactoring"
    label: "🧹 Refactoring"
  - text: "- [x] 🧪 Testing"
    label: "🧪 Testing"
  - text: "- [x] 🔧 Maintenance"
    label: "🔧 Maintenance"
  - text: "- [x] 🎽 CI"
    label: "🎽 CI"
  - text: "- [x] ⛓️ Dependencies"
    label: "⛓️ Dependencies"
  - text: "chore(deps): "
    label: "⛓️ Dependencies"
  - text: "- [x] 🧠 Meta"
    label: "🧠 Meta"
  - text: "Release v"
    label: "🚀 Release"
