[[lists]]
name = "list 1"

[[lists.feeds]]
title = "feed 1"
xmlUrl = "https://feed1.com/rss"
[[lists.feeds]]
title = "feed 2"
xmlUrl = "https://feed2.com/rss"


[[lists]]
name = "list 2"

[[lists.feeds]]
title = "feed 1"
xmlUrl = "https://feed1.com/rss"
[[lists.feeds]]
title = "feed 2"
xmlUrl = "https://feed2.com/rss"
