name: 🎉 Feature Request
description: Request a new feature or enhancement to an existing feature
labels: ["🎉 New Feature"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: ✏️ Describe the feature
      description: A clear and concise description
      placeholder: |
        - I want a feature to...
        - This behavior should be...
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: ✔︎ Confirm these checks
      description: Make sure you reviewed below
      options:
        - label: I searched the GitHub [Issues](https://github.com/5ouma/opml-generator/issues) or [Discussions](https://github.com/5ouma/opml-generator/discussions).
          required: true
        - label: I tried with the latest version.
          required: false
        - label: I agree to follow the [Code of Conduct](https://github.com/5ouma/opml-generator/blob/main/.github/CODE_OF_CONDUCT.md).
          required: true

  - type: textarea
    id: additional-info
    attributes:
      label: 🗒️ Additional Information
      description: Anything else you want to add
