name: 🦕 Setup Deno
description: Install Deno

runs:
  using: composite

  steps:
    - name: 🦕 Setup Deno
      uses: denoland/setup-deno@5e01c016a857a4dbb5afe9d0f9733cd472cba985 # v1.5.1
      with:
        deno-version: v1.x
