name: 🏷️ Label Past Pull Requests

on:
  pull_request:
    types: [closed]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  label-past-pr:
    name: 🏷️ Label Past Pull Requests
    permissions:
      pull-requests: write
    if: ${{ github.event.pull_request.user.login == 'renovate[bot]' && github.event.pull_request.merged }}
    runs-on: Ubuntu-Slim
    timeout-minutes: 1

    steps:
      - name: 🏷️ Add label to past Pull Requests
        uses: 5ouma/utils/label-past-pr@b70e56a2b532a6ab38bb6d1f6529835285109138 # v0.12.5
        with:
          label: 🕰️ Past Dependencies
