name: 🚸 pre-commit

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  pre-commit:
    name: 🚸 pre-commit
    runs-on: Ubuntu-Latest
    timeout-minutes: 5

    steps:
      - name: 🚸 Run pre-commit
        uses: 5ouma/utils/pre-commit@df69f0c1651b01a6d6074a6b6eb3a5be39e1d22a # v0.9.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
