name: 🚸 pre-commit

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: 🚸 pre-commit
    runs-on: Ubuntu-Latest
    timeout-minutes: 10

    steps:
      - name: 🚸 Run pre-commit
        uses: 5ouma/utils/pre-commit@9097ec305a581c6e204152e60da50c8dbfb4992d # v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
