name: 🚸 pre-commit

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: 🚸 pre-commit
    runs-on: Ubuntu-Latest
    timeout-minutes: 10

    steps:
      - name: 🚸 Run pre-commit
        uses: 5ouma/utils/pre-commit@bef1602ec7e587127ade273d6490f359c6fea95b # v0.12.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
