name: 🚀 Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  tagpr:
    name: 🔖 Release a New Version
    permissions:
      contents: write
      pull-requests: write
    runs-on: Ubuntu-Slim
    environment: Release
    timeout-minutes: 1
    outputs:
      tag: ${{ steps.tagpr.outputs.tag }}

    steps:
      - name: 💳 Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: 🚚 Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: true

      - name: 🏷️ Release a New Version
        id: tagpr
        uses: Songmu/tagpr@e7ae290f5cc5faabfdb4d131f8e4ce073ad8b3e2 # v1.18.0
        with:
          config: .github/tagpr.ini
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

  publish:
    name: 📦 Publish to JSR
    permissions:
      contents: read
      id-token: write
    needs: tagpr
    if: ${{ needs.tagpr.outputs.tag != '' }}
    runs-on: Ubuntu-Slim
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 📦 Publish to JSR
        run: npx jsr publish
